[2024-09-22T09:44:54.931+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-22T09:44:37.555895+00:00 [queued]>
[2024-09-22T09:44:54.946+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-22T09:44:37.555895+00:00 [queued]>
[2024-09-22T09:44:54.948+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-22T09:44:54.974+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-22 09:44:37.555895+00:00
[2024-09-22T09:44:54.993+0000] {standard_task_runner.py:57} INFO - Started process 326 to run task
[2024-09-22T09:44:55.006+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-22T09:44:37.555895+00:00', '--job-id', '1007', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpzmr36jg6']
[2024-09-22T09:44:55.012+0000] {standard_task_runner.py:85} INFO - Job 1007: Subtask get_flats
[2024-09-22T09:44:55.096+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-22T09:44:37.555895+00:00 [running]> on host 1646e3dc8472
[2024-09-22T09:44:55.352+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T09:44:37.555895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T09:44:37.555895+00:00'
[2024-09-22T09:44:57.037+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parser.py", line 152, in get_flats
    flat = flat | params | seller_data
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
[2024-09-22T09:44:57.069+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=get_flats, execution_date=20240922T094437, start_date=20240922T094454, end_date=20240922T094457
[2024-09-22T09:44:57.100+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1007 for task get_flats (unsupported operand type(s) for |: 'dict' and 'dict'; 326)
[2024-09-22T09:44:57.153+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-22T09:44:57.238+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
