[2024-09-29T07:08:24.305+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.transform_to_dims manual__2024-09-29T07:07:39.005816+00:00 [queued]>
[2024-09-29T07:08:24.316+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.transform_to_dims manual__2024-09-29T07:07:39.005816+00:00 [queued]>
[2024-09-29T07:08:24.317+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:08:24.337+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_to_dims> on 2024-09-29 07:07:39.005816+00:00
[2024-09-29T07:08:24.344+0000] {standard_task_runner.py:57} INFO - Started process 5986 to run task
[2024-09-29T07:08:24.350+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'transform_to_dims', 'manual__2024-09-29T07:07:39.005816+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpos_2u51f']
[2024-09-29T07:08:24.354+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask transform_to_dims
[2024-09-29T07:08:24.441+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.transform_to_dims manual__2024-09-29T07:07:39.005816+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:08:24.585+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='transform_to_dims' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T07:07:39.005816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T07:07:39.005816+00:00'
[2024-09-29T07:08:24.648+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/etl.py:161 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-29T07:08:24.652+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/etl.py:162 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-29T07:08:24.675+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/etl.py:211 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-29T07:08:24.678+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-29T07:08:24.705+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flats, task_id=transform_to_dims, execution_date=20240929T070739, start_date=20240929T070824, end_date=20240929T070824
[2024-09-29T07:08:24.742+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-29T07:08:24.820+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
