[2024-09-22T09:48:33.929+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_fact_table manual__2024-09-22T09:48:16.403045+00:00 [queued]>
[2024-09-22T09:48:33.945+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_fact_table manual__2024-09-22T09:48:16.403045+00:00 [queued]>
[2024-09-22T09:48:33.946+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-22T09:48:33.967+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_fact_table> on 2024-09-22 09:48:16.403045+00:00
[2024-09-22T09:48:33.977+0000] {standard_task_runner.py:57} INFO - Started process 411 to run task
[2024-09-22T09:48:33.982+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_fact_table', 'manual__2024-09-22T09:48:16.403045+00:00', '--job-id', '1011', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpt7b0p8oz']
[2024-09-22T09:48:33.985+0000] {standard_task_runner.py:85} INFO - Job 1011: Subtask create_fact_table
[2024-09-22T09:48:34.060+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_fact_table manual__2024-09-22T09:48:16.403045+00:00 [running]> on host 1646e3dc8472
[2024-09-22T09:48:34.307+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T09:48:16.403045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T09:48:16.403045+00:00'
[2024-09-22T09:48:34.317+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS fact_flat (
        metro_id SERIAL,
        text_id SERIAL,
        seller_id SERIAL,
        advt_id SERIAL,
        building_id SERIAL,
        flat_params_id SERIAL,
        district_id SERIAL,
        geo_id SERIAL,
        price DECIMAL
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    )
[2024-09-22T09:48:34.348+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T09:48:34.666+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T09:48:35.064+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  password authentication failed for user 'flat_store_owner'
connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  connection is insecure (try using `sslmode=require`)

[2024-09-22T09:48:35.082+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_fact_table, execution_date=20240922T094816, start_date=20240922T094833, end_date=20240922T094835
[2024-09-22T09:48:35.102+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1011 for task create_fact_table (connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  password authentication failed for user 'flat_store_owner'
connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  connection is insecure (try using `sslmode=require`)
; 411)
[2024-09-22T09:48:35.132+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-22T09:48:35.170+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
