[2024-09-22T09:44:55.030+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_fact_table manual__2024-09-22T09:44:37.555895+00:00 [queued]>
[2024-09-22T09:44:55.047+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_fact_table manual__2024-09-22T09:44:37.555895+00:00 [queued]>
[2024-09-22T09:44:55.049+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-22T09:44:55.068+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_fact_table> on 2024-09-22 09:44:37.555895+00:00
[2024-09-22T09:44:55.076+0000] {standard_task_runner.py:57} INFO - Started process 327 to run task
[2024-09-22T09:44:55.082+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_fact_table', 'manual__2024-09-22T09:44:37.555895+00:00', '--job-id', '1009', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpga6z6pok']
[2024-09-22T09:44:55.087+0000] {standard_task_runner.py:85} INFO - Job 1009: Subtask create_fact_table
[2024-09-22T09:44:55.285+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_fact_table manual__2024-09-22T09:44:37.555895+00:00 [running]> on host 1646e3dc8472
[2024-09-22T09:44:55.441+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T09:44:37.555895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T09:44:37.555895+00:00'
[2024-09-22T09:44:55.446+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS fact_flat (
        metro_id SERIAL,
        text_id SERIAL,
        seller_id SERIAL,
        advt_id SERIAL,
        building_id SERIAL,
        flat_params_id SERIAL,
        district_id SERIAL,
        geo_id SERIAL,
        price DECIMAL
        processed_dttm DATE NOT NULL,
        source VARCHAR(20) NOT NULL
    )
[2024-09-22T09:44:55.470+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T09:44:55.832+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-22T09:44:56.273+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  password authentication failed for user 'flat_store_owner'
connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  connection is insecure (try using `sslmode=require`)

[2024-09-22T09:44:56.287+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_fact_table, execution_date=20240922T094437, start_date=20240922T094455, end_date=20240922T094456
[2024-09-22T09:44:56.316+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1009 for task create_fact_table (connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  password authentication failed for user 'flat_store_owner'
connection to server at "p-gentle-bar-a2xkd23n.eu-central-1.aws.neon.tech" (3.126.212.11), port 5432 failed: ERROR:  connection is insecure (try using `sslmode=require`)
; 327)
[2024-09-22T09:44:56.361+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-22T09:44:56.440+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
