[2024-09-29T07:34:21.954+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:33:12.095005+00:00 [queued]>
[2024-09-29T07:34:21.999+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:33:12.095005+00:00 [queued]>
[2024-09-29T07:34:22.003+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:34:22.046+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-29 07:33:12.095005+00:00
[2024-09-29T07:34:22.132+0000] {standard_task_runner.py:57} INFO - Started process 6695 to run task
[2024-09-29T07:34:22.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-29T07:33:12.095005+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmp7jc7xhq_']
[2024-09-29T07:34:22.154+0000] {standard_task_runner.py:85} INFO - Job 173: Subtask get_flats
[2024-09-29T07:34:22.388+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-29T07:33:12.095005+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:34:22.641+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T07:33:12.095005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T07:33:12.095005+00:00'
[2024-09-29T07:37:05.969+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parser.py", line 151, in get_flats
    flat['description'] = soup.find_all("div", {'itemprop': "description"})[0].text
IndexError: list index out of range
[2024-09-29T07:37:05.989+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=get_flats, execution_date=20240929T073312, start_date=20240929T073421, end_date=20240929T073705
[2024-09-29T07:37:06.002+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 173 for task get_flats (list index out of range; 6695)
[2024-09-29T07:37:06.042+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-29T07:37:06.094+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
